version: "3.9"

networks:
  core-net:
    name: core-net

services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check=false
    ports:
      - "9092:9092"
    networks:
      - core-net

  redpanda-console:
    image: redpandadata/console:latest
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=redpanda:9092
    networks:
      - core-net

  jaeger:
    image: jaegertracing/all-in-one:1.51
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - core-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - core-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - core-net
    depends_on:
      - prometheus

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cg
      POSTGRES_PASSWORD: cg
      POSTGRES_DB: cityguide
    volumes:
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - core-net

  auth-profile:
    build: ./services/auth_profile
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://cg:cg@postgres:5432/cityguide
      JWT_SECRET: secret
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - postgres
      - redpanda
    networks:
      - core-net
    healthcheck:
      test:
        - CMD-SHELL
        - python -c "import urllib.request,sys;sys.exit(0 if urllib.request.urlopen('http://localhost:8000/healthz').status==200 else 1)"
      interval: 10s
      timeout: 5s
      retries: 5

  route-planner:
    build: ./services/route_planner
    ports:
      - "8002:8000"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda
    networks:
      - core-net
    healthcheck:
      test:
        - CMD-SHELL
        - python -c "import urllib.request,sys;sys.exit(0 if urllib.request.urlopen('http://localhost:8000/healthz').status==200 else 1)"
      interval: 10s
      timeout: 5s
      retries: 5

  orchestrator:
    build: ./services/orchestrator
    ports:
      - "8003:8000"
    environment:
      KAFKA_BROKERS: redpanda:9092
      POSTGRES_DSN: postgresql+asyncpg://cg:cg@postgres:5432/cityguide
    depends_on:
      - postgres
      - redpanda
    networks:
      - core-net
    healthcheck:
      test:
        - CMD-SHELL
        - python -c "import urllib.request,sys;sys.exit(0 if urllib.request.urlopen('http://localhost:8000/openapi.json').status==200 else 1)"
      interval: 10s
      timeout: 5s
      retries: 5

  story-service:
    build: ./services/story_service
    ports:
      - "8004:8000"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda
    networks:
      - core-net
    healthcheck:
      test:
        - CMD-SHELL
        - python -c "import urllib.request,sys;sys.exit(0 if urllib.request.urlopen('http://localhost:8000/healthz').status==200 else 1)"
      interval: 10s
      timeout: 5s
      retries: 5

  tts-service:
    build: ./services/tts_service
    ports:
      - "8005:8000"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda
    networks:
      - core-net
    healthcheck:
      test:
        - CMD-SHELL
        - python -c "import urllib.request,sys;sys.exit(0 if urllib.request.urlopen('http://localhost:8000/healthz').status==200 else 1)"
      interval: 10s
      timeout: 5s
      retries: 5

  delivery-prefetch:
    build: ./services/delivery_prefetch
    ports:
      - "8006:8000"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda
    networks:
      - core-net
    healthcheck:
      test:
        - CMD-SHELL
        - python -c "import urllib.request,sys;sys.exit(0 if urllib.request.urlopen('http://localhost:8000/healthz').status==200 else 1)"
      interval: 10s
      timeout: 5s
      retries: 5

  trip-runtime:
    build: ./services/trip_runtime
    ports:
      - "8007:8000"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda
    networks:
      - core-net
    healthcheck:
      test:
        - CMD-SHELL
        - python -c "import urllib.request,sys;sys.exit(0 if urllib.request.urlopen('http://localhost:8000/healthz').status==200 else 1)"
      interval: 10s
      timeout: 5s
      retries: 5

  paywall-billing:
    build: ./services/paywall_billing
    ports:
      - "8008:8000"
    networks:
      - core-net
    healthcheck:
      test:
        - CMD-SHELL
        - python -c "import urllib.request,sys;sys.exit(0 if urllib.request.urlopen('http://localhost:8000/healthz').status==200 else 1)"
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - route-planner
    networks:
      - core-net
