openapi: 3.0.3
info:
  title: Paywall Billing API
  version: 1.0.0
paths:
  /billing/paywall:
    post:
      summary: Process paywall billing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
      responses:
        '200':
          description: Billing result
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
